### ISSUE TITLE
BGR or RGB？

### ISSUE THREAD

**Issue by GreenTeaHua** [armstrong1972/pySample-for-ShiqiYu#1]
in the orgal libfacedetect:
//!!! The input image must be a #BGR# one (three-channel) instead of RGB
//	pResults = facedetect_cnn(pBuffer, (unsigned char*)(image.ptr(0)), image.cols, image.rows, (int)image.step);
and in this pySample-for-ShiqiYu:
//input image, it must be RGB (three-channel) image!原版要求BGR？
int * shiqi_fd(unsigned char * rgb_image_data, int width, int height, int step) 
{
	unsigned char * pBuffer = (unsigned char *)malloc(DETECT_BUFFER_SIZE);
	return facedetect_cnn(pBuffer, rgb_image_data, width, height, step);
}
??

**Comment by armstrong1972** [comment]
Hi GreenTea :

Personally, I think it does not matter whether RGB or BGR, which does not affect feature recognition, a person's features will not change when the color changes. 

Shiqi's interface need RGB , but you can get the feature by BGR also .
