### ISSUE TITLE
Ubuntu 下运行错误

### ISSUE THREAD

**Issue by AndyShaw2048** [armstrong1972/pySample-for-ShiqiYu#2]
你好，我在Ubuntu 16.04运行时，在载入dll的时候，出现了 invalid ELF header 错误
是只能在windows上运行吗？如果是，那怎么才能在Ubuntu上运行呢

谢谢

**Comment by AndyShaw2048** [comment]
打扰了，我自己重新编译为了.so，然后再调用就成功了。

**Comment by Ozone-oo** [comment]
你好，我想问下，你是如何编译成so文件的呢？

**Comment by Ozone-oo** [comment]
> 打扰了，我自己重新编译为了.so，然后再调用就成功了。

您好，能够告知如何调用so文件呢
